name = "fs"

[namespace.storage]
implement = ["copier", "mover"]

[namespace.storage.new]
optional = ["pair_policy", "work_dir"]

[namespace.storage.op.list]
optional = ["continuation_token","list_mode"]

[namespace.storage.op.read]
optional = ["offset", "io_callback", "size"]

[namespace.storage.op.write]
optional = ["content_md5", "content_type", "offset", "io_callback", "storage_class"]
